library(dplyr)
#url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
#download.file(url,destfile="dataset.zip",method="curl")
#unzip("dataset.zip",exdir = "./")
setwd("./UCI HAR Dataset")
cn <- read.table("features.txt",sep="",col.names=c("id","names"))
x_train <- read.table("train/X_train.txt", sep="",col.names=cn$names)
y_train <- read.table("train/Y_train.txt", sep="",col.names="activity")
subject_train <- read.table("train/subject_train.txt", sep="", col.names="subject_id")
x_test <- read.table("test/X_test.txt", sep="",col.names=cn$names)
y_test <- read.table("test/Y_test.txt", sep="",col.names="activity")
subject_test <- read.table("test/subject_test.txt", sep="", col.names="subject_id")
x_tt <- rbind(x_test,x_train)
y_tt <- rbind(y_test,y_train)
subject_id <- rbind(subject_test,subject_train)
valid_cn <- make.names(names=names(x_tt), unique=TRUE, allow_ = TRUE)
names(x_tt) <- valid_cn
x_tt_sub <- select(x_tt,matches("mean|std"),-matches("angle|meanFreq"))
x_tt_subset <- mutate(x_tt_sub, activity = factor(y_tt$activity,labels=c("WALKING", "WALKING_UPSTAIRS", "WALKING_DOWNSTAIRS", "SITTING", "STANDING", "LAYING") ), subjectid = factor(subject_id$subject_id))
xtt_gr_id_ac <- group_by(x_tt_subset, subjectid, activity)
summ <- summarise_each(xtt_gr_id_ac, funs(mean))
write.table(summ,file="tidy_data.txt",row.name=F)
